//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sample
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADDRESS
    {
        public int ADDR_ID { get; set; }
        public Nullable<int> ADDR_AR { get; set; }
        public string ADDR_NAME { get; set; }
        public string ADDR_BRANCH { get; set; }
        public string ADDR_TAXID { get; set; }
        public string ADDR_ADDB1 { get; set; }
        public string ADDR_ADDB2 { get; set; }
        public string ADDR_PROVINCE { get; set; }
        public string ADDR_POST { get; set; }
        public string ADDR_TEL { get; set; }
        public string ADDR_FAX { get; set; }
        public string ADDR_MAIL { get; set; }
        public string ADDR_WEB { get; set; }
        public string ADDR_REMARK { get; set; }
        public Nullable<bool> ADDR_STATUS { get; set; }
        public Nullable<System.DateTime> ADDR_CREATE { get; set; }
    }
}
