//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sample
{
    using System;
    using System.Collections.Generic;
    
    public partial class CODE_RUNNING
    {
        public int CR_ID { get; set; }
        public string CR_CODE { get; set; }
        public string CR_NAME { get; set; }
        public Nullable<byte> CR_TYPE { get; set; }
        public string CR_PREFIX { get; set; }
        public string CR_SEPARATE { get; set; }
        public Nullable<byte> CR_RUNNING { get; set; }
        public Nullable<bool> CR_STATUS { get; set; }
    }
}
