//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sample
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPANY
    {
        public int CMPN_ID { get; set; }
        public string CMPN_NAME { get; set; }
        public string CMPN_ADDB1 { get; set; }
        public string CMPN_ADDB2 { get; set; }
        public string CMPN_E_NAME { get; set; }
        public string CMPN_E_ADDB1 { get; set; }
        public string CMPN_E_ADDB2 { get; set; }
        public string CMPN_POST { get; set; }
        public string CMPN_TEL { get; set; }
        public string CMPN_FAX { get; set; }
        public string CMPN_TAXID { get; set; }
        public string CMPN_REGNO { get; set; }
        public string CMPN_WEB { get; set; }
        public string CMPN_MAIL { get; set; }
        public Nullable<decimal> CMPN_VAT_R { get; set; }
        public byte[] CMPN_IMAGE { get; set; }
        public string CMPN_IMAGE_PATH { get; set; }
    }
}
