//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sample
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        public int CUS_ID { get; set; }
        public string CUS_CODE { get; set; }
        public string CUS_NAME { get; set; }
        public string CUS_BRANCH { get; set; }
        public string CUS_TAXID { get; set; }
        public string CUS_ADDB1 { get; set; }
        public string CUS_ADDB2 { get; set; }
        public string CUS_PROVINCE { get; set; }
        public string CUS_POST { get; set; }
        public string CUS_TEL { get; set; }
        public string CUS_FAX { get; set; }
        public string CUS_MAIL { get; set; }
        public string CUS_WEB { get; set; }
        public Nullable<int> CUS_CAT { get; set; }
        public Nullable<int> CUS_SLMN { get; set; }
        public string CUS_CONTACT { get; set; }
        public Nullable<short> CUS_CREDIT_TERM { get; set; }
        public Nullable<decimal> CUS_CREDIT_LIMIT { get; set; }
        public Nullable<decimal> CUS_DISC_PERCEN { get; set; }
        public Nullable<byte> CUS_TAX_TY { get; set; }
        public Nullable<byte> CUS_TAX_VATIO { get; set; }
        public string CUS_REMARK { get; set; }
        public Nullable<bool> CUS_STATUS { get; set; }
        public Nullable<System.DateTime> CUS_CREATE { get; set; }
    }
}
