//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sample
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCTYPE
    {
        public int DT_ID { get; set; }
        public string DT_CODE { get; set; }
        public string DT_NAME { get; set; }
        public Nullable<byte> DT_TYPE { get; set; }
        public string DT_PREFIX { get; set; }
        public string DT_SEPARATE { get; set; }
        public Nullable<bool> DT_DATE_SELECT { get; set; }
        public Nullable<byte> DT_DATE_TYPE { get; set; }
        public Nullable<int> DT_DATE_DIGIT { get; set; }
        public string DT_DATE_SEPARATE { get; set; }
        public Nullable<byte> DT_RUNNING { get; set; }
        public Nullable<bool> DT_STATUS { get; set; }
        public Nullable<byte> DT_PRINT_TY { get; set; }
    }
}
